package hubdle.ecosystem.feature.install.tasks

import java.io.File
import javax.inject.Inject
import org.gradle.api.DefaultTask
import org.gradle.api.Project
import org.gradle.api.file.Directory
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.ProjectLayout
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.model.ObjectFactory
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import org.gradle.kotlin.dsl.register

@CacheableTask
public abstract class InstallPreCommitTask
@Inject
constructor(layout: ProjectLayout, objects: ObjectFactory) : InstallTask, DefaultTask() {

    init {
        group = "install"
    }

    @get:Input public abstract val preCommitName: Property<String>

    @OutputDirectory
    public val preCommitOutputDir: DirectoryProperty =
        objects.directoryProperty().convention(layout.preCommitHubdleDir.dir("pre-commits"))

    @get:OutputFile
    public val preCommitOutputFile: RegularFileProperty =
        objects
            .fileProperty()
            .convention(
                preCommitOutputDir.zip(preCommitName) { preCommitOutputDir, preCommitName ->
                    preCommitOutputDir.file("${preCommitName}.pre-commit")
                }
            )

    @TaskAction override fun install(): Unit = Unit

    public companion object {
        public const val NAME: String = "installPreCommit"

        internal fun register(project: Project) =
            project.tasks.register<InstallPreCommitTask>(NAME).configure { task ->
                task.preCommitName.set("")
            }
    }
}

internal fun InstallPreCommitTask.createInstallPreCommitGradleTask() {
    val headerText = "[${preCommitName.get()} autogenerated by `Hubdle` plugin]"
    val text =
        """
        |
        |# $headerText
        |./gradlew ${preCommitName.get()}
        |"""
            .trimMargin()

    preCommitOutputFile.asFile.get().apply {
        parentFile.mkdirs()
        writeText(text)
    }
}

internal val ProjectLayout.preCommitFile: File
    get() = projectDirectory.file(".git/hooks/pre-commit").asFile

internal val ProjectLayout.preCommitHubdleFile: File
    get() = projectDirectory.file(".git/hooks/.hubdle/pre-commit").asFile

internal val ProjectLayout.preCommitHubdleDir: Directory
    get() = projectDirectory.dir(".git/hooks/.hubdle")
