package com.javiersc.hubdle.extensions.config.install.commit

import com.javiersc.gradle.extensions.maybeRegisterLazily
import com.javiersc.hubdle.extensions.config.install.InstallTask
import java.io.File
import javax.inject.Inject
import org.gradle.api.DefaultTask
import org.gradle.api.Project
import org.gradle.api.file.ProjectLayout
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.OutputFile

@CacheableTask
public abstract class InstallPreCommitTask
@Inject
constructor(
    layout: ProjectLayout,
) : InstallTask, DefaultTask() {

    init {
        group = "install"
    }

    @get:Input public abstract val preCommitName: String

    @OutputDirectory
    public val preCommitOutputDir: File =
        layout.buildDirectory.asFile.get().resolve("install/pre-commits/")

    @get:OutputFile
    public val preCommitOutputFile: File
        get() = preCommitOutputDir.resolve("$preCommitName.pre-commit")

    public companion object {
        public const val name: String = "installPreCommit"

        internal fun register(project: Project) =
            project.tasks.maybeRegisterLazily<InstallPreCommitTask>(name)
    }
}

internal fun InstallPreCommitTask.createInstallPreCommitGradleTask() {
    val headerText = "[$preCommitName autogenerated by `javiersc-all-projects` plugin]"
    val text =
        """
            |
            |# $headerText
            |./gradlew $preCommitName
            |
        """.trimMargin()

    preCommitOutputFile.writeText(text)
}

internal val Project.preCommitFile: File
    get() {
        check(this == rootProject) { "This task should be only configured in the root project" }
        return file("${layout.projectDirectory.asFile}/.git/hooks/pre-commit")
    }
