name: add-element-to-hubdle-catalog

on:
  workflow_dispatch:
    inputs:
      module:
        description: 'Library module'
        type: string
        required: false
      plugin_id:
        description: 'Plugin ID'
        type: string
        required: false
      version:
        description: 'Version'
        type: string
        required: false
      version_ref:
        description: 'versionRef'
        type: string
        required: false
      ignore:
        description: 'ignore'
        type: boolean
        default: false
        required: false

jobs:
  add-element:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: JavierSegoviaCordoba/actions/git/checkout@main
        with:
          token: '${{ secrets.TOKEN_GITHUB_ACTION }}'

      - name: Add element to Hubdle catalog
        run: kotlin .scripts/add-element-to-hubdle-catalog.kts module=${{ github.event.inputs.module }} id=${{ github.event.inputs.plugin_id }} version=${{ github.event.inputs.version }} versionRef=${{ github.event.inputs.version_ref }} ignore=${{ github.event.inputs.ignore }}

      - name: Commit library
        if: ${{ github.event.inputs.module != null }}
        uses: JavierSegoviaCordoba/actions/git/commit@main
        with:
          message: 'Add library ${{ github.event.inputs.module }} to Hubdle catalog'
          push: true

      - name: Commit plugin
        if: ${{ github.event.inputs.plugin_id != null }}
        uses: JavierSegoviaCordoba/actions/git/commit@main
        with:
          message: 'Add plugin ${{ github.event.inputs.plugin_id }} to Hubdle catalog'
          push: true
